def enrich_country_only_direct() -> None:
    path = OUTPUT_DIR / "artist_universe_country_only.csv"
    df = collapse_merge_columns(pd.read_csv(path, low_memory=False))
    report_missingness(df, "country_only before enrichment")

    df = apply_place_parsing(df)
    df = clean_birth_geography(df)
    df = resolve_missing_qids_from_names(df, "artist_universe_country_only_name_to_qid.csv")
    df = enrich_from_wikidata_qids(df, "artist_universe_country_only_targeted_wikidata.csv")
    df = enrich_from_wikipedia_sources(df, "country_artists")
    df = resolve_missing_musicbrainz_mbids(df, "artist_universe_country_only_name_to_musicbrainz.csv")
    df = builder.targeted_musicbrainz_bio_enrichment(builder.session(), df, INTERMEDIATE_DIR / "artist_universe_country_only_targeted_musicbrainz_bio.csv")
    df = enrich_from_musicbrainz_generic(df, "artist_universe_country_only_generic_musicbrainz.csv")
    df = enrich_from_wikipedia_origin_years(df, "artist_universe_country_only_wikipedia_origin_years.csv")
    df = enrich_with_discogs_and_itunes(df, "artist_universe_country_only_discogs_itunes.csv")
    df = enrich_from_official_websites(df, "artist_universe_country_only_official_websites.csv")
    df = apply_web_confirmed_overrides(df)
    df = apply_group_and_occupation_annotations(df)
    df = apply_place_parsing(df)
    df = clean_birth_geography(df)
    df = infer_state_from_existing_city_country(df)
    df = refresh_country_only_derived_columns(df)
    report_missingness(df, "country_only after enrichment")
    save_country_only_dataset(df)
